### ISSUE TITLE
Error listing containers

### ISSUE THREAD

**Issue by Amolith** [TronFortyTwo/OnTheRoad#12]
I have no idea how to help or give you more information so you tell me what to do and I'll gladly do it!

I ran `otr` for the first time, downloaded the binary, and created a container named `ubports`. When I got back to the main menu, I wanted to use the container so I selected that option and, instead of listing the created containers, it output the following:
```
Traceback (most recent call last):
  File "/usr/bin/libertine-container-manager", line 313, in <module>
    container_manager = LibertineContainerManager()
  File "/usr/bin/libertine-container-manager", line 35, in __init__
    self.containers_config = ContainersConfig()
  File "/usr/lib/python3/dist-packages/libertine/ContainersConfig.py", line 64, in __init__
    self.refresh_database()
  File "/usr/lib/python3/dist-packages/libertine/ContainersConfig.py", line 167, in refresh_database
    self.container_list = read_container_config_file()
  File "/usr/lib/python3/dist-packages/libertine/ContainersConfig.py", line 31, in read_container_config_file
    container_list = json.load(fd)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 12 column 5 (char 288)
```

Like I said, I'll help in any way I can, I just don't have the first idea of how other than posting this report with the error.

**Comment by TronFortyTwo** [comment]
I see. That sometimes happens the first time because Libertine mess up the configuration file because was externally modified.
Do a complete reset in the danger zone in otr (warning: will delete all your libertine and OnTheRoad containers), and new containers won't make any problem.
Alternatively you can fix the configuration file by hand but unless there's a reason to do that doing a reset is better.

**Comment by TronFortyTwo** [comment]
After some investigation I track down the origin of the problem, I will fix it asap
